language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - python3-notify2
      - python-notify2
      - dbus

install:
  - python setup.py install
  - pip install coveralls
script:
  - coverage run --source=forex_python -m unittest discover

after_success:
  coveralls
